In [ ]:
#Question 1 
#How to print NDimensional array of zeros with numpy

In [3]:
import numpy as np
x = np.zeros((4,4))

In [4]:
x

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
#Question 2 >How to convert a list into numpy array

In [6]:
l=[1,2,3,4,5]
np.array(l)

array([1, 2, 3, 4, 5])

In [7]:
#Question 3 >How to create an array between two numbers with arrange in numpy

In [9]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
#Question 4 >How to create an array between two numbers with desired steps with arrange in numpy

In [11]:
np.arange(1,100,20)

array([ 1, 21, 41, 61, 81])

In [12]:
#Question 5 >How to find the shape of an array with np

In [13]:
x.shape

(4, 4)

In [14]:
#Question 6 >How to find the datatype of an array with np
x.dtype



dtype('float64')

In [15]:
#Question 7 >How to create an array of random numbers with np

In [16]:
a=np.random.randn((10))

In [17]:
a

array([-0.62012506, -1.04589459, -1.4670013 ,  0.81138168,  1.1223849 ,
        0.80178828,  0.35445483, -0.63949691, -0.90515824, -0.38001322])

In [18]:
b=np.random.randn((10))
b

array([ 1.9338793 ,  0.97640259, -0.51133415,  0.39498239,  0.41005578,
       -2.28942743, -0.6709332 , -0.57247221,  1.37800057,  0.85589293])

In [19]:
#Question 8 >How to add two arrays with np

In [20]:
a+b

array([ 1.31375424, -0.069492  , -1.97833545,  1.20636407,  1.53244068,
       -1.48763915, -0.31647837, -1.21196912,  0.47284233,  0.47587971])

In [21]:
#Question 9 >How to subtract two arrays with np

In [22]:
a-b

array([-2.55400437, -2.02229718, -0.95566715,  0.41639929,  0.71232912,
        3.09121571,  1.02538802, -0.0670247 , -2.28315881, -1.23590615])

In [23]:
#Question 10 >How to multiply any number with  arrays with np

In [24]:
2*a

array([-1.24025013, -2.09178918, -2.93400261,  1.62276336,  2.2447698 ,
        1.60357656,  0.70890965, -1.27899382, -1.81031648, -0.76002644])

In [25]:
#Question 11 >How to inverse the columns
1/a

array([-1.61257795, -0.95611929, -0.68166265,  1.23246559,  0.89095996,
        1.24721205,  2.82123397, -1.56372922, -1.10477921, -2.63148739])

In [26]:
#Question 12 >How to find the positive elements of arrays with np
a>0

array([False, False, False,  True,  True,  True,  True, False, False,
       False])

In [27]:
a[a>0]

array([0.81138168, 1.1223849 , 0.80178828, 0.35445483])

In [28]:
#Indexing of array
#Q13 how to find the value at a particular index in 

In [29]:
p = np.array([1,2,3,4,5])

In [30]:
p[2]

3

In [31]:
#Q14 Boolean indexing
p>0

array([ True,  True,  True,  True,  True])

In [32]:
p[p>0]

array([1, 2, 3, 4, 5])

In [34]:
#Q15 Fancy Indexing
p[[4,3]]

array([5, 4])

In [36]:
#Slicing of array

g =np.random.rand(10,10)

In [37]:
g

array([[0.85568312, 0.90743003, 0.80770316, 0.6143714 , 0.01426747,
        0.15801462, 0.49859948, 0.89833208, 0.70965758, 0.38962672],
       [0.78203827, 0.20457668, 0.11484916, 0.77559412, 0.94973468,
        0.06291989, 0.55786047, 0.35052188, 0.12621711, 0.07049539],
       [0.52261841, 0.88845249, 0.59211541, 0.4063528 , 0.57799964,
        0.29352259, 0.05900791, 0.44272217, 0.29937321, 0.85535945],
       [0.00580114, 0.47592663, 0.86216679, 0.80374156, 0.00489992,
        0.45309398, 0.21666387, 0.37390291, 0.68091449, 0.71019489],
       [0.72908417, 0.79522251, 0.04164932, 0.12343844, 0.66723266,
        0.39487179, 0.15826618, 0.16092667, 0.60950396, 0.0650353 ],
       [0.48803311, 0.47656417, 0.00106675, 0.72966454, 0.9972329 ,
        0.96530687, 0.17806141, 0.00104748, 0.41321706, 0.02605729],
       [0.13167974, 0.83192079, 0.3227427 , 0.573028  , 0.35458299,
        0.69624779, 0.04553196, 0.99411255, 0.25181191, 0.88383685],
       [0.15935367, 0.29452056, 0.8847713

In [38]:
#Q16 Slicing a particular row 
g[0]

array([0.85568312, 0.90743003, 0.80770316, 0.6143714 , 0.01426747,
       0.15801462, 0.49859948, 0.89833208, 0.70965758, 0.38962672])

In [39]:
#Q17 slicing particular row and particular column of a row
g[0][3]

0.6143714006624876

In [40]:
#Q18 how to slice particular rows and columns with any desired steps
g[1:10:3]

array([[0.78203827, 0.20457668, 0.11484916, 0.77559412, 0.94973468,
        0.06291989, 0.55786047, 0.35052188, 0.12621711, 0.07049539],
       [0.72908417, 0.79522251, 0.04164932, 0.12343844, 0.66723266,
        0.39487179, 0.15826618, 0.16092667, 0.60950396, 0.0650353 ],
       [0.15935367, 0.29452056, 0.88477131, 0.77635424, 0.29253018,
        0.94397016, 0.17835506, 0.02385538, 0.06945302, 0.85376638]])

In [41]:
#19 Slicing on particulr columns

In [42]:
g[::,0:3]

array([[0.85568312, 0.90743003, 0.80770316],
       [0.78203827, 0.20457668, 0.11484916],
       [0.52261841, 0.88845249, 0.59211541],
       [0.00580114, 0.47592663, 0.86216679],
       [0.72908417, 0.79522251, 0.04164932],
       [0.48803311, 0.47656417, 0.00106675],
       [0.13167974, 0.83192079, 0.3227427 ],
       [0.15935367, 0.29452056, 0.88477131],
       [0.86150487, 0.88558403, 0.53708219],
       [0.20382232, 0.53857717, 0.44825574]])

In [44]:
#Question 20 how to create a square having 1 at all borders and 0 inside it
s = np.ones((5,5))

In [45]:
s

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [46]:
s[1:-1,1:-1] = 0
s

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
#Q21 How to find the square root of all numbers in array using NP


In [49]:
h=np.array([4,9,16,25])
np.sqrt(h)

array([2., 3., 4., 5.])

In [50]:
#Q22 How to find the square of all numbers in array using NP

In [51]:
np.power(h,2)

array([ 16,  81, 256, 625], dtype=int32)

In [54]:
#Q23 How to find the larger number from two arrays using NP
r = [12,13,4,5]
r

[12, 13, 4, 5]

In [55]:
np.maximum(h,r)

array([12, 13, 16, 25])

In [56]:
#Q24 where function in np
np.where(h>15,"15 say bada h","15 say chota h")

array(['15 say chota h', '15 say chota h', '15 say bada h',
       '15 say bada h'], dtype='<U14')

In [57]:
#Q25 Mean of an array
np.mean(r)

8.5

In [58]:
#Q26 Commulative sum of array
np.cumsum(r)

array([12, 25, 29, 34], dtype=int32)

In [59]:
#Q27 commulative product
np.cumprod(r)

array([  12,  156,  624, 3120], dtype=int32)

In [60]:
#Q28 Boolean Sum
b=h>6
b


array([False,  True,  True,  True])

In [61]:
b.sum()

3

In [62]:
#Q29 If any value is true?
b.any()


True

In [63]:
#Q30 if all values are true
b.all()

False

In [64]:
#Q31 sorting values of list
g.sort()
g

array([[0.01426747, 0.15801462, 0.38962672, 0.49859948, 0.6143714 ,
        0.70965758, 0.80770316, 0.85568312, 0.89833208, 0.90743003],
       [0.06291989, 0.07049539, 0.11484916, 0.12621711, 0.20457668,
        0.35052188, 0.55786047, 0.77559412, 0.78203827, 0.94973468],
       [0.05900791, 0.29352259, 0.29937321, 0.4063528 , 0.44272217,
        0.52261841, 0.57799964, 0.59211541, 0.85535945, 0.88845249],
       [0.00489992, 0.00580114, 0.21666387, 0.37390291, 0.45309398,
        0.47592663, 0.68091449, 0.71019489, 0.80374156, 0.86216679],
       [0.04164932, 0.0650353 , 0.12343844, 0.15826618, 0.16092667,
        0.39487179, 0.60950396, 0.66723266, 0.72908417, 0.79522251],
       [0.00104748, 0.00106675, 0.02605729, 0.17806141, 0.41321706,
        0.47656417, 0.48803311, 0.72966454, 0.96530687, 0.9972329 ],
       [0.04553196, 0.13167974, 0.25181191, 0.3227427 , 0.35458299,
        0.573028  , 0.69624779, 0.83192079, 0.88383685, 0.99411255],
       [0.02385538, 0.06945302, 0.1593536

In [65]:
r.sort()
r

[4, 5, 12, 13]

In [66]:
#Q32 finding unique elements of array
np.unique(r)

array([ 4,  5, 12, 13])

In [67]:
i=np.random.randn(3,2)

In [68]:
j=np.random.randn(2,3)

In [69]:
#Q33 dot product of matrices

i.dot(j)

array([[ 0.41977893, -0.47500645, -3.25190166],
       [-0.14956157,  0.17843157,  1.46655717],
       [ 0.40672442, -0.27971775,  2.89608794]])

In [70]:
#Q34 find transpose
i.transpose()

array([[-0.77689851,  0.30102207, -0.2770847 ],
       [-0.7615468 ,  0.35806055,  0.96519539]])

In [71]:
#Q35 find trace of 
i.trace()

-0.41883795928984197

In [72]:
#Q36 find the version of NP
print(np.__version__)

1.19.2


In [73]:
#Q37 find the odd numbers in array
arr = np.array([1,2,3,4,5,6,7,8,9])
arr[arr%2 ==1]

array([1, 3, 5, 7, 9])

In [74]:
#Q38 replace all odd numbers with -1
arr[arr%2 ==1]=-1

In [75]:
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [76]:
#Q39 find common between two arrays
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

In [77]:
#Q40 remove all elements which are comon
np.setdiff1d(a,b)

array([1, 3, 5, 6])

In [78]:
#Q41 find median of array
np.median(a)

3.0

In [82]:
#Q42 create a 1D array

has = np.arange(10)
has

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [83]:
#Q43 create a boolean array
np.full((3, 3), True, dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [84]:
#Q44 reshape an array
moh = np.arange(10)
moh.reshape(2, -1) 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [87]:
#Q45 stack d and e vertically
d = np.arange(10).reshape(2,-1)
e = np.repeat(1, 10).reshape(2,-1)
np.concatenate([d, e], axis=0)




array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [88]:
#Q46 stack d and e horizontally
d = np.arange(10).reshape(2,-1)
e = np.repeat(1, 10).reshape(2,-1)
np.concatenate([d, e], axis=1)



array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [89]:
#Q47 How to extract all numbers between a given range from a numpy array?
a = np.arange(15)

index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 5,  6,  7,  8,  9, 10])

In [93]:
#Q48 How to drop all missing values from a numpy array
z = np.array([1,2,3,np.nan,5,6,7,np.nan])
z[~np.isnan(z)]

array([1., 2., 3., 5., 6., 7.])

In [94]:
#Q49 How to compute the euclidean distance between two arrays
a = np.array([1,2,3,4,5])
b = np.array([4,5,6,7,8])
dist = np.linalg.norm(a-b)
dist

6.708203932499369

In [95]:
#Q50  How to find all the local maxima (or peaks) in a 1d array
a = np.array([1, 3, 7, 1, 2, 6, 0, 1])
doublediff = np.diff(np.sign(np.diff(a)))
peak_locations = np.where(doublediff == -2)[0] + 1
peak_locations

array([2, 5], dtype=int64)

In [96]:
pip install nbconvert

In [97]:
conda install nbconvert

Note: you may need to restart the kernel to use updated packages.

Solving environment: ...working... done

# All requested packages already installed.

